version: '3.9'

services:
  backend_server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/opt/services/backend
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - 80:80

