version: '3.9'

services:
  database1:
    image: postgres:alpine
    restart: on-failure
    container_name: db_postgres
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - ./utils.sh:/docker-entrypoint-initdb.d/utils.sh
      - database1_volume:/var/lib/postgresql/data
    networks:
      - fullstack

  backend_server:
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/opt/services/backend
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - fullstack
    depends_on:
      - database1


volumes:
  database1_volume:

networks:
  fullstack:
    driver: bridge