"""Init2

Revision ID: 4d52116478c5
Revises: d20ecbc4d2b2
Create Date: 2021-10-15 23:18:59.975709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d52116478c5'
down_revision = 'd20ecbc4d2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_hidden_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'user_hidden_name')
    # ### end Alembic commands ###
